### ISSUE TITLE
resin.models.device.has() now breaks if an 'undefined' parameter is passed

### ISSUE THREAD

**Issue by lekkas** [resin-io/resin-sdk#274]
sdk version: `resin-sdk@^6.0.0-beta2`

This is a breaking change that breaks the unpublished [master branch](https://github.com/resin-io/resin-cli/commit/9214cb0d90610968362c567a00eb19af256f611a) of `resin-cli`

Stack:

```
kostasl@macbook:~/resin/github/resin-io-modules/resin-sync (master) $ DEBUG=1 resinstaging ssh
TypeError: Cannot read property 'length' of undefined
    at Object.exports.get (/usr/local/lib/node_modules/resin-cli/node_modules/resin-sdk/build/models/device.js:230:31)
    at Object.exports.has (/usr/local/lib/node_modules/resin-cli/node_modules/resin-sdk/build/models/device.js:425:20)
    at Command.action (/usr/local/lib/node_modules/resin-cli/build/actions/ssh.js:68:34)
    at /usr/local/lib/node_modules/resin-cli/node_modules/capitano/build/command.js:96:21
    at tryCatcher (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by pimterry** [comment]
Fixed in 6.0.0.
