### ISSUE TITLE
ResinRequestError: Request error: Unauthorized

### ISSUE THREAD

**Issue by kranthisai** [resin-io/resin-sdk#355]
Got the following error
/home/kranthi/workspace/resin/resin-log/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^
ResinRequestError: Request error: Unauthorized
    at /home/kranthi/workspace/resin/resin-log/node_modules/resin-request/build/request.js:198:17
    at tryCatcher (/home/kranthi/workspace/resin/resin-log/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kranthi/workspace/resin/resin-log/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/kranthi/workspace/resin/resin-log/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/kranthi/workspace/resin/resin-log/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/kranthi/workspace/resin/resin-log/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/kranthi/workspace/resin/resin-log/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/kranthi/workspace/resin/resin-log/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/kranthi/workspace/resin/resin-log/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

code;
-------
`var resin = require('resin-sdk')({
    apiUrl: "https://api.resin.io/"
});

const credentials = {
    username: '********',
    password: '*********'
};

resin.auth.login(credentials, function(error) {
    if (error) throw error;
});`

**Comment by pimterry** [comment]
@kranthisai Ah, I can see what's gone wrong there. See [the `.login()` docs](https://github.com/resin-io/resin-sdk/blob/master/DOCUMENTATION.md#resin.auth.login): it takes an object with an `email` property, not a `username`. Let me know if that solves your issue, and I can investigate further if not.

**Comment by kranthisai** [comment]
Thanks @pimterry . It works.
