### ISSUE TITLE
Module wont load - v6.14.4

### ISSUE THREAD

**Issue by davemcdonnell** [resin-io/resin-sdk#402]
v6.14.4 wont load with node.js.

```
dmcdonnell-ml:node_modules dmcdonne$ resin
{ Error: Cannot find module 'resin-sdk'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/resin-cli/node_modules/resin-sdk-preconfigured/build/index.js:11:18
    at /usr/local/lib/node_modules/resin-cli/node_modules/resin-sdk-preconfigured/build/index.js:3:17
    at Object.<anonymous> (/usr/local/lib/node_modules/resin-cli/node_modules/resin-sdk-preconfigured/build/index.js:9:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/resin-cli/build/app.js:67:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/resin-cli/bin/resin:2:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3 code: 'MODULE_NOT_FOUND' }
```

I had to install v6.14.3 to get resin-cli working.

**Comment by pimterry** [comment]
This was due to a buggy release yesterday evening that was missing some essential files. We've now deprecated that version, and changed the default version to install in npm back to 6.14.3, which should resolve this for all new installs.

Thanks for the report!
