### ISSUE TITLE
Tests should pass against staging or a devenv

### ISSUE THREAD

**Issue by pimterry** [resin-io/resin-sdk#413]
It'd be really useful for testing SDK compatibility before deploys, and for testing major API changes if the tests passed out of the box when run against staging or a local devenv. At the moment there's a selection of failures that we have to just ignore. These include:

* Lots of billing methods
* The test that actually tries to hit a device URL
* Maybe some others?

(there's some instability in the staging API that makes this tricky right now, but we should do this soonish, once we're happy that's sorted)

**Comment by thgreasi** [comment]
Interesting observation, running only the application & billing tests against staging or devenv seem to always work.
On the other hand when running the full suit I get `401 ResinRequestError: Request error: Unauthorized` on the billing tests, even though an Authorization token is provided.
The billings tests fail for the free user & are skipped for the paid user (reasonable in case it's not found).

**Comment by pimterry** [comment]
Hmm, curious. I have no idea why that might be. Try to isolate it down to a single test that if you run first, breaks the billing tests? Let me know if you want a hand investigating some time.

**Comment by MoranF** [comment]
```
1) Billing Model Free Account resin.models.billing.getAccount() should not return a billing account info object:
     AssertionError: expected { Object (body, statusCode, ...) } to have a property 'statusCode' of 404, but got 401
      at tests/integration/models/billing.spec.coffee:25:42
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

  2) Billing Model Free Account resin.models.billing.getPlan() should return a free tier billing plan object:
     ResinRequestError: Request error: Unauthorized
      at node_modules/resin-request/build/request.js:201:17
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

  3) Billing Model Free Account resin.models.billing.getBillingInfo() should return a free tier billing info object:
     ResinRequestError: Request error: Unauthorized
      at node_modules/resin-request/build/request.js:201:17
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

  4) Billing Model Free Account resin.models.billing.updateBillingInfo() should throw when no parameters are provided:
     AssertionError: expected promise to be rejected with an error including 'Token not provided.' but got 'Request error: Unauthorized'
  

  5) Billing Model Free Account resin.models.billing.updateBillingInfo() should throw when an token_id is not provided:
     AssertionError: expected promise to be rejected with an error including 'Token not provided.' but got 'Request error: Unauthorized'
  

  6) Billing Model Free Account resin.models.billing.getInvoices() should return no invoices:
     ResinRequestError: Request error: Unauthorized
      at node_modules/resin-request/build/request.js:201:17
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

**Comment by thgreasi** [comment]
Reconfirmed that running only the billing tests works (master against staging).
Additionally, I think that I narrowed this down a bit (by using several `.only` statments and re-running). It seems that billing tests fail when [`getSdk.fromSharedOptions` test](https://github.com/resin-io/resin-sdk/blob/b325c57bc87877740d20bc35da6eead598b6ca35/tests/integration/resin.spec.coffee#L106-L120) runs. Does that rings any bell @pimterry ?

**Comment by pimterry** [comment]
No idea, sorry. Sounds like a bug though - I can't think of any good reason that that test would affect how the billing tests work.

**Comment by thgreasi** [comment]
Especially affecting in a way that it would only fail against the devenv and staging only.
